image: maven:3.9.2
clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
    maven: ~/.m2 # Defines maven cache


  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B clean install # Combines compile and test, and adds clean for a fresh build
        artifacts:
          - target/**
          - target/surefire-reports/**arget/surefire-reports/**

    - step: &sonarcloud-analysis
        name: SonarCloud Analysis
        caches:
          - maven
          - sonar
        script:
          - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        artifacts:
          - target/**

    - step: &push-to-aws-ecr
        name: Build Image and Push to AWS ECR
        trigger: manual
        script:
          # Execute versioning script and capture new version and build the docker image
          - |
            IFS=' ' read -r captured_version captured_suffix <<< $(./version-manager.sh)
            docker build -t xxxxxx/project_name:$captured_version .
            if [ -n "$captured_suffix" ]; then
              docker tag xxxxxx/project_name:$captured_version xxxxxx/project_name:$captured_suffix
            fi
            docker tag xxxxxx/project_name:$captured_version xxxxxx/project_name:latest
          # Use the pipe to push the image to AWS ECR
          - pipe: atlassian/aws-ecr-push-image:2.3.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: project_name
              ECR_PUBLIC: "true"
              PUBLIC_REGISTRY_ALIAS: xxxxxx


pipelines:
  branches:
    develop:
      - parallel:
          - step: *build-test
          - step: *sonarcloud-analysis
      - step: *push-to-aws-ecr

    main:
      - parallel:
          - step: *build-test
          - step: *sonarcloud-analysis
      - step: *push-to-aws-ecr

  pull-requests:
    '**':
      - parallel:
          - step: *build-test
          - step: *sonarcloud-analysis
