version: '3.8'

services:
  db:
    build: 
      context: ./database
    environment:
      POSTGRES_DB: meine_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  microservice_one:
    build: 
      context: ./backend_services/microservice_1
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/meine_db
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - db

  microservice_two:
    build:
      context: ./backend_services/microservice_2
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/meine_db
    ports:
      - "8001:8001"
    depends_on:
      - db
      - microservice_one

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: http://microservice_one:8000
    ports:
      - "3000:80"
    depends_on:
      - microservice_one

volumes:
  postgres_data:
