openapi: 3.0.0
info:
  title: Comments API
  version: "1.0"
paths:
  /comments/:
    post:
      summary: Create a new comment
      description: This endpoint is used to create a new comment.
      operationId: createComment
      requestBody:
        description: Comment creation request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentCreate'
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentCreate'
        '400':
          description: Invalid input

  /posts/{post_id}/comments/:
    get:
      summary: Get comments for a specific post
      description: This endpoint retrieves all comments associated with a specific post.
      operationId: getCommentsByPost
      parameters:
        - name: post_id
          in: path
          required: true
          description: Unique ID of the post
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: An array of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

components:
  schemas:
    CommentCreate:
      type: object
      required:
        - account_id
        - post_id
        - text
      properties:
        account_id:
          type: integer
          format: int64
          description: Unique ID of the account
        post_id:
          type: integer
          format: int64
          description: Unique ID of the post
        text:
          type: string
          description: Text content of the comment

    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID of the comment
        account_id:
          type: integer
          format: int64
          description: Unique ID of the account that made the comment
        post_id:
          type: integer
          format: int64
          description: Unique ID of the post associated with the comment
        text:
          type: string
          description: Text content of the comment
        created_at:
          type: string
          format: date-time
          description: Timestamp of when the comment was created
