apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: consumer-one
  name: consumer-one
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer-one
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/social-media-platform-default: "true"
        io.kompose.service: consumer-one
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: post_queue
            - name: MICROSERVICE_5_API_URL
              value: http://microservice_five:8005/optimize/
          image: consumer-one
          name: consumer-one
      restartPolicy: Always
