apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: consumer-two
  name: consumer-two
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer-two
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/social-media-platform-default: "true"
        io.kompose.service: consumer-two
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: comment_queue
            - name: MICROSERVICE_3_API_URL
              value: http://microservice_six:8006/classify/
          image: consumer-two
          name: consumer-two
      restartPolicy: Always
