apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        env:
        - name: VITE_URL_MICROSERVICE_ONE
          # Durch das Portfowarding im Makefile (beim erstellen des Clusters) kann der MS 1 von außerhalb des Clusters über diese IP erreicht werden.
          value: http://localhost:8083
          #value: http://microservice-one-service:8001          
        image: registry:5000/social-media-platform_frontend:latest
        ports:
        - containerPort: 80
          protocol: TCP
