apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-two
  name: microservice-two-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-two
  template:
    metadata:
      labels:
        app: microservice-two
    spec:
      containers:
        - name: microservice-two
          image: registry:5000/social-media-platform_microservice_two:latest
          ports:
            - containerPort: 8002
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@database-service:5432/meine_db"
            - name: FRONTEND_URL
              value: "http://localhost:8082"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KAFKA_TOPIC
              value: post_queue

      restartPolicy: Always
