apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: microservice-five
  name: microservice-five
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-five
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/social-media-platform-default: "true"
        io.kompose.service: microservice-five
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://user:password@db:5432/meine_db
          image: microservice-five
          name: microservice-five
          ports:
            - containerPort: 8005
              hostPort: 8005
              protocol: TCP
      restartPolicy: Always
