apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-one
  name: microservice-one-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: microservice-one
  template:
    metadata:
      labels:
        app: microservice-one
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://user:password@db:5432/meine_db
            - name: FRONTEND_URL
              value: http://localhost:3000
          image: microservice-one
          name: microservice-one
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
