apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-one
  name: microservice-four-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-one
  template:
    metadata:
      labels:
        app: microservice-one
    spec:
      containers:
        - name: microservice-four
          image: registry:5000/social-media-platform_microservice_four:latest
          ports:
            - containerPort: 8004
              protocol: TCP
          env:
          - name: DATABASE_URL
            value: "postgresql://user:password@database-service:5432/meine_db"
          - name: FRONTEND_URL
            value: "http://localhost:8082"
      restartPolicy: Always
