apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-one
  name: microservice-one-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: microservice-one
  template:
    metadata:
      labels:
        app: microservice-one
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              # database-service ist funktioniert wegen dem DNS was im Cluster bereitgestellt wird
              value: "postgresql://user:password@database-service:5432/meine_db"
            - name: FRONTEND_URL
              # Durch das Portfowarding im Makefile (beim erstellen des Clusters)läuft das Frontend außerhalb des Clusters auf der abgegeben IP.
              value: "http://localhost:8082"
              #value: "http://frontend-service:3000"

          image: registry:5000/social-media-platform_microservice_one:latest
          name: microservice-one
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
