apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: websocket-client-1
  name: websocket-client-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-client-1
  template:
    metadata:
      labels:
        app: websocket-client-1
    spec:
      containers:
        - name: websocket-client-1
          image: registry:5000/social-media-platform_websocket_client_1:latest
          ports:
            - containerPort: 8021
              protocol: TCP
          env:
            - name: WEBSOCKET_PORT
              value: "8765"
            - name: WEBSOCKET_SERVER_HOST
              value: websocket-server-service
      restartPolicy: Always
