apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: kafka-init
  name: kafka-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-init
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/social-media-platform-default: "true"
        io.kompose.service: kafka-init
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka:9092
            - name: KAFKA_TOPIC_ONE
              value: post_queue
            - name: KAFKA_TOPIC_THREE
              value: classified_comments_queue
            - name: KAFKA_TOPIC_TWO
              value: comment_queue
          image: kafka-init
          name: kafka-init
      restartPolicy: Always
