apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: websocket-server
  name: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/social-media-platform-default: "true"
        io.kompose.service: websocket-server
    spec:
      containers:
        - env:
            - name: WEBSOCKET_SERVER_HOST
              value: 0.0.0.0
            - name: WEBSOCKET_SERVER_PORT
              value: "8765"
          image: websocket-server
          name: websocket-server
          ports:
            - containerPort: 8765
              hostPort: 8765
              protocol: TCP
      restartPolicy: Always
