apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /tmp/k3dvol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node
          operator: In
          values:
          - agent0