apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30080
      targetPort: 80
  type: LoadBalancer
  
