apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-one
  name: microservice-four-service
spec:
  selector:
    app: microservice-one
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8004
      nodePort: 30085
  type: NodePort
