apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-two
  name: microservice_two-service
spec:
  selector:
    app: microservice-two
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
      nodePort: 30083
  type: NodePort
