apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: microservice-five
  name: microservice_five
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8005
  selector:
    io.kompose.service: microservice-five
