apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-five
  name: microservice_five-service
spec:
  selector:
    app: microservice-five
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8005
  type: ClusterIP

