apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-one
  name: microservice-one-service
spec:
  selector:
    app: microservice-one
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001

