apiVersion: v1
kind: Service
metadata:
  labels:
    app: websocket-server
  name: websocket-server-service
spec:
  selector:
    app: websocket-server
  ports:
    - name: "8765"
      port: 8765
      targetPort: 8765
      nodePort: 30082
  type: NodePort


