apiVersion: v1
kind: Service
metadata:
  labels:
    app: websocket-client-1
  name: websocket-client-1-service
spec:
  selector:
    app: websocket-client-1
  ports:
    - name: "8021"
      port: 8021
      targetPort: 8021
  type: ClusterIP

