apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  type: ClusterIP

