name: Build and Push Docker Image

on:
  push:
    branches: [feature_action_herbert_5]
    # or use 'pull_request' with 'types: [closed]' for merged PRs
    # pull_request:
    #   types: [closed]
    #   branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: IvanBirkamier
        password: dckr_pat_0XbRWB1EDWqF23JnG-Xhvd7ouIw

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          IvanBirkamier/social_media_app_university_projekt:${{ github.run_number }}
          IvanBirkamier/social_media_app_university_projekt:latest
