name: Run Tests on Push to feature_actions_herbert

on:
  push:
    branches: [feature_actions_herbert]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'
    - name: Install Dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd backend/test
        pytest
